version: '3.1'

services:
  mcaptcha:
    image: mcaptcha/showcase:latest
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres # set password at placeholder
      MCAPTCHA_REDIS_URL: redis://mcaptcha-redis/
      MCAPTCHA_CAPTCHA_SITEKEY: "UjlhvnNxM8ILneMoQQB8bHI6kcpDOYNV"
      RUST_LOG: debug
    volumes:
      - ./config/:/etc/mcaptcha-showcase/
